name: Platform Management

on:
  workflow_dispatch:
    inputs:
      provisionShared:
        description: "Provision Shared Resources"
        type: boolean
        required: false

      target:
        description: "Environment to deploy to"
        required: true
        default: "dev"
        type: choice
        options:
          - production
          - staging
          - dev

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  Provision_Shared_Resources:
    name: Provision Shared Resources
    runs-on: ubuntu-latest
    environment: ${{ inputs.target }}
    if: |
      !failure() && !cancelled() &&
      (
        github.event.inputs.provisionShared == 'true'
      )
    steps:
      - name: Check out code from GitHub
        uses: actions/checkout@v5

      - name: Create Resources
        id: task-create-resources
        run: |

          echo ${{ inputs.target }}
          
          ./script/devops_provision_shared.sh
