name: Platform Management

on:
  workflow_dispatch:
    inputs:
      provisionShared:
        description: "Provision Shared Resources"
        type: boolean
        required: false

      provisionSolution:
        description: "Provision Solution Resources"
        type: boolean
        required: false

      deployContainer:
        description: "Deploy Container Instance"
        type: boolean
        required: false

      target:
        description: "Environment to deploy to"
        required: true
        default: "dev"
        type: choice
        options:
          - production
          - staging
          - dev

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  Provision_Solution_Resources:
    name: Provision Solution Resources
    runs-on: ubuntu-latest
    environment: ${{ inputs.target }}
    env:
      ENVIRONMENT: ${{ vars.ENVIRONMENT  }}
      LOCATION: ${{ vars.LOCATION }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
      KEY_VAULT_NAME: ${{ vars.KEY_VAULT_NAME }}
      
    if: |
      !failure() && !cancelled() && 
      (
        github.event.inputs.provisionSolution == 'true'
      )
    steps:
      - name: Check out code from GitHub
        uses: actions/checkout@v5

      - name: OIDC Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.CICD_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.SUBSCRIPTION_ID }}

      - name: Create Resources
        id: task-create-resources
        run: |
          ./script/devops_provision.sh
  Provision_Shared_Resources:
    name: Provision Shared Resources
    runs-on: ubuntu-latest
    environment: ${{ inputs.target }}
    env:
      ENVIRONMENT: ${{ vars.ENVIRONMENT  }}
      LOCATION: ${{ vars.LOCATION }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
      
    if: |
      !failure() && !cancelled() &&
      (
        github.event.inputs.provisionShared == 'true'
      )
    steps:
      - name: Check out code from GitHub
        uses: actions/checkout@v5

      - name: OIDC Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.CICD_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.SUBSCRIPTION_ID }}

      - name: Create Resources
        id: task-create-resources
        run: |
          ./script/devops_provision_shared.sh
  Deploy_Container_Instance:
    name: Deploy Container Instance
    runs-on: ubuntu-latest
    environment: ${{ inputs.target }}
    env:
      ENVIRONMENT: ${{ vars.ENVIRONMENT  }}
      LOCATION: ${{ vars.LOCATION }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
    if : |
      !failure() && !cancelled() && 
      (
        github.event.inputs.deployContainer == 'true'
      )
    steps:
      - name: Check out code from GitHub
        uses: actions/checkout@v5

      - name: OIDC Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.CICD_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.SUBSCRIPTION_ID }}

      - name: Deploy Container Instance
        id: task-deploy-container
        run: |
          echo "Deploying Container Instance to $ENVIRONMENT"